server:
  port: 8443

# mybatis
mybatis:
  # mapper 파일 위치 지정
  mapper-locations: classpath:/mappers/**/*.xml
  # model 프로퍼티 camel case 설정
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.asianaidt.springmvc.step03: debug